### ISSUE TITLE
Priority things to take care off

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-unicycle-frenzy#51]
**Game loop:**

@youhavehowie I thought about the game loop and am curious about where you stand on it now..  I really enjoyed maps like Steps for playing in lobbies & racing against people.  The longer/more difficult maps like Bookworm I'd prefer to play for the completion + reward or to improve my time, as it usually took much more than 15 minutes to get a good playthrough - and often ended up being a solo experience.

We can use the new [in-menu settings](https://files.facepunch.com/crayz/1b2511b1/sbox-dev_Shj52nwrqA.png) to help players understand what they're getting into.  The simplest might be a difficulty dropdown (easy, medium, hard, impossible) - with the map pool adjusting to the selection.

I've also thought about a dropdown with different types of gameplay, something like racing and adventure.  In racing you compete for ~15 minutes on a map like Steps.  in adventure, you go for achievements and completions.  But then I wonder if we're better off solidifying a single game loop, and in that case perhaps racing is a better path forward for brand new players?

**Priority issues:**

- [ ] #46 - The framework is there, but still missing achievement integration & persistent state
- [x] #43 
- [ ] #36 - Do a pass on controller gameplay, I'm sure there's a few things left to tighten up there
- [x] #27 - Last I checked sprays don't show at all anymore
- [x] #48

**Comment by youhavehowie** [comment]
Yea I think that's a really good point about the length of the map relating to how competitive it feels. I think the most fun I've had would probably be on hop-stop or even the tutorial map oddly(without the stop gates) because they're mostly easy to complete but hard to master and the skill comes more from how you can exploit the map.

This gives me some second thoughts on the FRENZY letters though because they were more of a response to giving less skilled players something to shoot for on the longer more difficult courses. They still serve a purpose on those maps but on the shorter maps it would be a harder mechanic to implement and more of a distraction than anything. It feels odd to only have the letters on the more difficult maps though. 

I definitely like the idea of giving the courses a difficulty rating system but I'm not sure if it should be an in-menu setting. We talked about including a symbol like ski slopes have(green circle, blue square, black diamond) in the map thumbnails and I think that would serve our needs. When players vote for the next map in game they can see the difficulty for all the options there as well, we can make sure there is always a variety of difficulties to vote for and the difficulty will be set by vote instead of a menu setting.

I'm sure Lewis can do much better but just an idea of what it could look like, easy, medium, hard is probably more clear than the ski slope symbols
![image](https://user-images.githubusercontent.com/11905265/186766405-4a2ef744-1d35-4530-9653-16674385b69e.png)

**Comment by youhavehowie** [comment]
also as for adventure mode, I agree we should solidify/prioritize the racing gamemode first and down the line we can look into making maps/challenges more tailored around that idea.

**Comment by youhavehowie** [comment]
Thinking about this more, I think the FRENZY letters would still work on any map and would be a fun challenge for any player. I want to rethink how I was placing them though in my example screenshots of Pop-Rock, I'd like to try and keep all the letters on the main path of the map and use them more to encourage players to take the risky/hard jumps rather than as a side objective that doesn't teach you the map.
