### ISSUE TITLE
Finish the Tutorial Map

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#59]
```[tasklist]
### Tasks
- [ ] when the player crosses the finish line give them a good job message and ask if they want to try and beat the medal times/collect frenzy letters or return to the main menu
- [ ] after a tutorial hint is closed show current tutorial text on screen for player to reference while playing and an option to reopen the current tutorial hint to watch the tutorial video again
- [ ] instead of dead stopping the player when they activate a tutorial hint have time slow down and lerp into a complete stop
- [ ] art/polish - this is a larger issue, see Map Art
```
Some other general notes
- Make the track more interesting from a medal time perspective, the map should serve as a tutorial first and foremost but if there are some interesting changes we can make to the layout to make getting the medal times more fun we should do that
- I think once we get that final finish line message in and fix the sticking issues we can start doing to do some internal testing and get feedback
